version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: money_transfer_db
    environment:
      POSTGRES_DB: money_transfer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
